src/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('customer/', include('customer.urls')),
]

src/customer/urls.py
from django.urls import path

from .views import CustomerListView

app_name = 'customer'

urlpatterns = [
    path('list/', CustomerListView.as_view(), name='customer-list')
]

src/core/models.py
from django.db import models

# Create your models here.

src/customer/models.py
from django.db import models


class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    birth_date = models.DateField()
    area_code = models.CharField(max_length=3)
    phone_number = models.CharField(max_length=9)
    country = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    objects = models.Manager()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_full_phone_number(self):
        return f'({self.area_code}) {self.phone_number}'
    
    class Meta:
        db_table = 'customer'

src/core/views.py
from django.shortcuts import render

# Create your views here.

src/customer/views.py
from django.views.generic import ListView

from .models import Customer

class CustomerListView(ListView):
    template_name = 'customer/customer_list.html'
    model = Customer
    queryset = Customer.objects.all()

src/core/templates/index.html
{% extends "model_page.html" %}

{% block content %}
    <h1>CRM</h1>
{% endblock %}

src/core/templates/model_footer.html
<div class="container text-center">
    <small>Desenvolvido por Rafael Morán</small>
</div>

src/core/templates/model_header.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href={% url 'index' %}>CRM</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'customer:customer-list' %}">Clientes</a>
        </li>
    </ul>
</nav>

src/core/templates/model_page.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body class="d-flex flex-column">
        <header>
            {% include "model_header.html" %}
        </header>

        <main class="content" style="margin-top: 5%">
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </main>        

        <footer class="py-4 bg-dark text-white-50">
            {% include "model_footer.html" %}
        </footer>

    </body>
    <style>
        html, body {
            height: 100%;
        }
        main {
            flex: 1 0 auto;
        }
        footer {
            flex-shrink: none;
            margin-top: 2em;
        }
    </style>
</html>

src/customer/templates/customer/customer_list.html
{% extends "model_page.html" %}

{% block content %}
    <h2>Clientes</h2>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Cidade</th>
                <th>Telefone</th>
                <th>E-mail</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customer_list %}
                <tr>
                    <td>{{ customer.first_name }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.get_full_phone_number }}</td>
                    <td>{{ customer.email }}</td>
                    <td><button type="button" class="btn btn-danger">Excluir</button></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}